# @format
bot:
  ID: ''
  TOKEN: ''
  PREFIX: '!'
  EMBED_COLOR: '#2f3136'
  OWNERS: ['1139950107995934863', '1220040643766915112']
  MONGO: ''
links:
  INVITE: 'https://discord.com/oauth2/authorize?client_id=1032300215664914523&permissions=8&scope=applications.commands%20bot'
  SUPPORT: 'https://discord.gg/flare'
  VOTE: 'https://top.gg/bot/1032300215664914523/vote'