# @format
bot:
  ID: '990134647335813160'
  TOKEN: 'MTI0Njc5ODYzMzAwNTc0ODI3Ng.GvyOwo.KhPPoWYOJeqz3qSzrk2X2OyJwVKSu4g75gHb24'
  PREFIX: '!'
  EMBED_COLOR: '#2f3136'
  OWNERS: ['1139950107995934863', '1220040643766915112']
  MONGO: 'mongodb+srv://neonplayz:neonop1337@cluster0.hz4ryoh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
links:
  INVITE: 'https://discord.com/oauth2/authorize?client_id=1032300215664914523&permissions=8&scope=applications.commands%20bot'
  SUPPORT: 'https://discord.gg/abusement'
  VOTE: 'https://top.gg/bot/1032300215664914523/vote'